сумма двух чисел
js-tasks-ru/jsbasic-20240219_marina77 pull request #1
Opened 2024-02-28 20:21 UTC by moiseyka86

2024-02-28 20:21 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @koalex должен запустить тесты.

2024-02-29 05:40 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-02-29 05:42 UTC, koalex requested changes
Исправить замечания

2024-02-29 05:42 UTC, koalex commented on 0-module/1-task/index.js
> +  console.log (m+n);
`return m + n;`
Никаких `console.log`-ов

2024-02-29 05:42 UTC, koalex commented on 1-module/1-task/index.js
> +   console.log("факториал " + n + " равен " + fac);
`return fac;` Никаких `console.log`-ов

2024-03-04 13:34 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-03-04 13:47 UTC, koalex approved these changes

2024-03-04 13:47 UTC, koalex commented on 2-module/1-task/index.js
> +  }
где `return sum;`

2024-03-04 13:47 UTC, koalex commented on 2-module/2-task/index.js
> + if (massiv.length > 0) return true
Наоборот

2024-03-04 13:47 UTC, koalex commented on 1-module/2-task/index.js
> +  if ((name.length >= 4) && !name.includes(" ")) {
Проверка что **name** является строкой

2024-03-04 13:47 UTC, koalex commented on 1-module/5-task/index.js
> +  alert(newstr);
Удалить **alert**

2024-03-04 13:47 UTC, koalex commented on 1-module/5-task/index.js
> +  alert(newstr);
Вернуть `newStr`

2024-03-04 13:48 UTC, merged